// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/ledger.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSETS      AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITIES AccountType = 2
	AccountType_ACCOUNT_TYPE_EQUITIES    AccountType = 3
	AccountType_ACCOUNT_TYPE_INCOMES     AccountType = 4
	AccountType_ACCOUNT_TYPE_EXPENSES    AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSETS",
		2: "ACCOUNT_TYPE_LIABILITIES",
		3: "ACCOUNT_TYPE_EQUITIES",
		4: "ACCOUNT_TYPE_INCOMES",
		5: "ACCOUNT_TYPE_EXPENSES",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSETS":      1,
		"ACCOUNT_TYPE_LIABILITIES": 2,
		"ACCOUNT_TYPE_EQUITIES":    3,
		"ACCOUNT_TYPE_INCOMES":     4,
		"ACCOUNT_TYPE_EXPENSES":    5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_ledger_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_ledger_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

type MetadataFilter_Operator int32

const (
	MetadataFilter_OPERATOR_UNSPECIFIED           MetadataFilter_Operator = 0
	MetadataFilter_OPERATOR_EQUAL                 MetadataFilter_Operator = 1
	MetadataFilter_OPERATOR_NOT_EQUAL             MetadataFilter_Operator = 2
	MetadataFilter_OPERATOR_GREATER_THAN          MetadataFilter_Operator = 3
	MetadataFilter_OPERATOR_LESS_THAN             MetadataFilter_Operator = 4
	MetadataFilter_OPERATOR_GREATER_THAN_OR_EQUAL MetadataFilter_Operator = 5
	MetadataFilter_OPERATOR_LESS_THAN_OR_EQUAL    MetadataFilter_Operator = 6
	MetadataFilter_OPERATOR_PARTIAL_MATCH         MetadataFilter_Operator = 7 // e.g., String contains or regex
)

// Enum value maps for MetadataFilter_Operator.
var (
	MetadataFilter_Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_EQUAL",
		2: "OPERATOR_NOT_EQUAL",
		3: "OPERATOR_GREATER_THAN",
		4: "OPERATOR_LESS_THAN",
		5: "OPERATOR_GREATER_THAN_OR_EQUAL",
		6: "OPERATOR_LESS_THAN_OR_EQUAL",
		7: "OPERATOR_PARTIAL_MATCH",
	}
	MetadataFilter_Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED":           0,
		"OPERATOR_EQUAL":                 1,
		"OPERATOR_NOT_EQUAL":             2,
		"OPERATOR_GREATER_THAN":          3,
		"OPERATOR_LESS_THAN":             4,
		"OPERATOR_GREATER_THAN_OR_EQUAL": 5,
		"OPERATOR_LESS_THAN_OR_EQUAL":    6,
		"OPERATOR_PARTIAL_MATCH":         7,
	}
)

func (x MetadataFilter_Operator) Enum() *MetadataFilter_Operator {
	p := new(MetadataFilter_Operator)
	*p = x
	return p
}

func (x MetadataFilter_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataFilter_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_ledger_proto_enumTypes[1].Descriptor()
}

func (MetadataFilter_Operator) Type() protoreflect.EnumType {
	return &file_api_proto_v1_ledger_proto_enumTypes[1]
}

func (x MetadataFilter_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataFilter_Operator.Descriptor instead.
func (MetadataFilter_Operator) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{8, 0}
}

type AccountName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=v1.AccountType" json:"type,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // Optional, can be empty or "*".
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // The specific account name or wildcard "*".
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountName) Reset() {
	*x = AccountName{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountName) ProtoMessage() {}

func (x *AccountName) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountName.ProtoReflect.Descriptor instead.
func (*AccountName) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *AccountName) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AccountName) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AccountName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Account       *AccountName           `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Amount        *money.Money           `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance       *money.Money           `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Posting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Posting) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Posting) GetAccount() *AccountName {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Posting) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Posting) GetBalance() *money.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Posting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Note           string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Metadata       map[string]*anypb.Any  `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postings       []*Posting             `protobuf:"bytes,6,rep,name=postings,proto3" json:"postings,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transaction) GetMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RecordTransactionRequest struct {
	state                     protoimpl.MessageState                   `protogen:"open.v1"`
	IdempotencyKey            string                                   `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Date                      *timestamppb.Timestamp                   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Note                      string                                   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Metadata                  map[string]*anypb.Any                    `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postings                  []*RecordTransactionRequest_PostingInput `protobuf:"bytes,5,rep,name=postings,proto3" json:"postings,omitempty"`
	VerifyNonNegativeBalances []*AccountName                           `protobuf:"bytes,6,rep,name=verify_non_negative_balances,json=verifyNonNegativeBalances,proto3" json:"verify_non_negative_balances,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RecordTransactionRequest) Reset() {
	*x = RecordTransactionRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionRequest) ProtoMessage() {}

func (x *RecordTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionRequest.ProtoReflect.Descriptor instead.
func (*RecordTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *RecordTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RecordTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RecordTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RecordTransactionRequest) GetMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecordTransactionRequest) GetPostings() []*RecordTransactionRequest_PostingInput {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *RecordTransactionRequest) GetVerifyNonNegativeBalances() []*AccountName {
	if x != nil {
		return x.VerifyNonNegativeBalances
	}
	return nil
}

type RecordTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionResponse) Reset() {
	*x = RecordTransactionResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionResponse) ProtoMessage() {}

func (x *RecordTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionResponse.ProtoReflect.Descriptor instead.
func (*RecordTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *RecordTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountName           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`   // Structured target. Empty user or name fields will be treated as wildcards like `*`.
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // Optional currency filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceRequest) Reset() {
	*x = GetAccountBalanceRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceRequest) ProtoMessage() {}

func (x *GetAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountBalanceRequest) GetAccount() *AccountName {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*AccountBalance      `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceResponse) Reset() {
	*x = GetAccountBalanceResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceResponse) ProtoMessage() {}

func (x *GetAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountBalanceResponse) GetBalances() []*AccountBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type AccountBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountName           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Balance       *money.Money           `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *AccountBalance) GetAccount() *AccountName {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountBalance) GetBalance() *money.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AccountBalance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MetadataFilter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // The metadata key to match on
	Operator      MetadataFilter_Operator `protobuf:"varint,2,opt,name=operator,proto3,enum=v1.MetadataFilter_Operator" json:"operator,omitempty"`
	Value         *anypb.Any              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // The value to compare against
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataFilter) Reset() {
	*x = MetadataFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataFilter) ProtoMessage() {}

func (x *MetadataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataFilter.ProtoReflect.Descriptor instead.
func (*MetadataFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataFilter) GetOperator() MetadataFilter_Operator {
	if x != nil {
		return x.Operator
	}
	return MetadataFilter_OPERATOR_UNSPECIFIED
}

func (x *MetadataFilter) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type TransactionFilter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey  []string               `protobuf:"bytes,2,rep,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	StartDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Note            string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"` // Partial match on the transaction note (wildcards supported by the repository adapter)
	MetadataFilters []*MetadataFilter      `protobuf:"bytes,6,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty"`
	Currency        string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"` // Optional currency filter for transactions
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionFilter) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TransactionFilter) GetIdempotencyKey() []string {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *TransactionFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TransactionFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *TransactionFilter) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *TransactionFilter) GetMetadataFilters() []*MetadataFilter {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

func (x *TransactionFilter) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *TransactionFilter     `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	OrderByDesc   bool                   `protobuf:"varint,4,opt,name=order_by_desc,json=orderByDesc,proto3" json:"order_by_desc,omitempty"` // If true, sort descending (newest first). If false, sort ascending.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListTransactionsRequest) GetOrderByDesc() bool {
	if x != nil {
		return x.OrderByDesc
	}
	return false
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PostingFilter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionFilter *TransactionFilter     `protobuf:"bytes,1,opt,name=transaction_filter,json=transactionFilter,proto3" json:"transaction_filter,omitempty"` // Carry over all transaction-level filters to filter the postings.
	Id                []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	TransactionId     []string               `protobuf:"bytes,3,rep,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Account           *AccountName           `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"` // Structured target. Unspecified account type, empty user or name fields will be treated as wildcards like `*`.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostingFilter) Reset() {
	*x = PostingFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingFilter) ProtoMessage() {}

func (x *PostingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingFilter.ProtoReflect.Descriptor instead.
func (*PostingFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *PostingFilter) GetTransactionFilter() *TransactionFilter {
	if x != nil {
		return x.TransactionFilter
	}
	return nil
}

func (x *PostingFilter) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PostingFilter) GetTransactionId() []string {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *PostingFilter) GetAccount() *AccountName {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListPostingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PostingFilter         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	OrderByDesc   bool                   `protobuf:"varint,4,opt,name=order_by_desc,json=orderByDesc,proto3" json:"order_by_desc,omitempty"` // If true, sort descending (newest first). If false, sort ascending.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostingsRequest) Reset() {
	*x = ListPostingsRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostingsRequest) ProtoMessage() {}

func (x *ListPostingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostingsRequest.ProtoReflect.Descriptor instead.
func (*ListPostingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostingsRequest) GetFilter() *PostingFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListPostingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPostingsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListPostingsRequest) GetOrderByDesc() bool {
	if x != nil {
		return x.OrderByDesc
	}
	return false
}

type ListPostingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostingsResponse) Reset() {
	*x = ListPostingsResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostingsResponse) ProtoMessage() {}

func (x *ListPostingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostingsResponse.ProtoReflect.Descriptor instead.
func (*ListPostingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *ListPostingsResponse) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *ListPostingsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RecordTransactionRequest_PostingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountName           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount        *money.Money           `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionRequest_PostingInput) Reset() {
	*x = RecordTransactionRequest_PostingInput{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionRequest_PostingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionRequest_PostingInput) ProtoMessage() {}

func (x *RecordTransactionRequest_PostingInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionRequest_PostingInput.ProtoReflect.Descriptor instead.
func (*RecordTransactionRequest_PostingInput) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RecordTransactionRequest_PostingInput) GetAccount() *AccountName {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RecordTransactionRequest_PostingInput) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_api_proto_v1_ledger_proto protoreflect.FileDescriptor

const file_api_proto_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/ledger.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x17google/type/money.proto\x1a\x1aapi/proto/v1/options.proto\"Z\n" +
	"\vAccountName\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.v1.AccountTypeR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x80\x02\n" +
	"\aPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12)\n" +
	"\aaccount\x18\x03 \x01(\v2\x0f.v1.AccountNameR\aaccount\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.google.type.MoneyR\x06amount\x12,\n" +
	"\abalance\x18\x05 \x01(\v2\x12.google.type.MoneyR\abalance\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfc\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x129\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1d.v1.Transaction.MetadataEntryR\bmetadata\x12'\n" +
	"\bpostings\x18\x06 \x03(\v2\v.v1.PostingR\bpostings\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xa2\x04\n" +
	"\x18RecordTransactionRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.v1.RecordTransactionRequest.MetadataEntryR\bmetadata\x12E\n" +
	"\bpostings\x18\x05 \x03(\v2).v1.RecordTransactionRequest.PostingInputR\bpostings\x12P\n" +
	"\x1cverify_non_negative_balances\x18\x06 \x03(\v2\x0f.v1.AccountNameR\x19verifyNonNegativeBalances\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1ae\n" +
	"\fPostingInput\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.v1.AccountNameR\aaccount\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.google.type.MoneyR\x06amount\"N\n" +
	"\x19RecordTransactionResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.v1.TransactionR\vtransaction\"a\n" +
	"\x18GetAccountBalanceRequest\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.v1.AccountNameR\aaccount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"K\n" +
	"\x19GetAccountBalanceResponse\x12.\n" +
	"\bbalances\x18\x01 \x03(\v2\x12.v1.AccountBalanceR\bbalances\"\xa4\x01\n" +
	"\x0eAccountBalance\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.v1.AccountNameR\aaccount\x12,\n" +
	"\abalance\x18\x02 \x01(\v2\x12.google.type.MoneyR\abalance\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xee\x02\n" +
	"\x0eMetadataFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1b.v1.MetadataFilter.OperatorR\boperator\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xe4\x01\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eOPERATOR_EQUAL\x10\x01\x12\x16\n" +
	"\x12OPERATOR_NOT_EQUAL\x10\x02\x12\x19\n" +
	"\x15OPERATOR_GREATER_THAN\x10\x03\x12\x16\n" +
	"\x12OPERATOR_LESS_THAN\x10\x04\x12\"\n" +
	"\x1eOPERATOR_GREATER_THAN_OR_EQUAL\x10\x05\x12\x1f\n" +
	"\x1bOPERATOR_LESS_THAN_OR_EQUAL\x10\x06\x12\x1a\n" +
	"\x16OPERATOR_PARTIAL_MATCH\x10\a\"\xad\x02\n" +
	"\x11TransactionFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x03(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12=\n" +
	"\x10metadata_filters\x18\x06 \x03(\v2\x12.v1.MetadataFilterR\x0fmetadataFilters\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\"\xaa\x01\n" +
	"\x17ListTransactionsRequest\x12-\n" +
	"\x06filter\x18\x01 \x01(\v2\x15.v1.TransactionFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\"\n" +
	"\rorder_by_desc\x18\x04 \x01(\bR\vorderByDesc\"p\n" +
	"\x18ListTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xb7\x01\n" +
	"\rPostingFilter\x12D\n" +
	"\x12transaction_filter\x18\x01 \x01(\v2\x15.v1.TransactionFilterR\x11transactionFilter\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x03 \x03(\tR\rtransactionId\x12)\n" +
	"\aaccount\x18\x04 \x01(\v2\x0f.v1.AccountNameR\aaccount\"\xa2\x01\n" +
	"\x13ListPostingsRequest\x12)\n" +
	"\x06filter\x18\x01 \x01(\v2\x11.v1.PostingFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\"\n" +
	"\rorder_by_desc\x18\x04 \x01(\bR\vorderByDesc\"`\n" +
	"\x14ListPostingsResponse\x12'\n" +
	"\bpostings\x18\x01 \x03(\v2\v.v1.PostingR\bpostings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount*\xb2\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACCOUNT_TYPE_ASSETS\x10\x01\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_LIABILITIES\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_TYPE_EQUITIES\x10\x03\x12\x18\n" +
	"\x14ACCOUNT_TYPE_INCOMES\x10\x04\x12\x19\n" +
	"\x15ACCOUNT_TYPE_EXPENSES\x10\x052\xa2\x04\n" +
	"\rLedgerService\x12\x85\x01\n" +
	"\x11RecordTransaction\x12\x1c.v1.RecordTransactionRequest\x1a\x1d.v1.RecordTransactionResponse\"3\x82\xb5\x18\r\x12\x05admin\x12\x04user\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/ledger/transactions\x12\x89\x01\n" +
	"\x11GetAccountBalance\x12\x1c.v1.GetAccountBalanceRequest\x1a\x1d.v1.GetAccountBalanceResponse\"7\x82\xb5\x18\r\x12\x05admin\x12\x04user\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/ledger/accounts/balance\x12\x82\x01\n" +
	"\x10ListTransactions\x12\x1b.v1.ListTransactionsRequest\x1a\x1c.v1.ListTransactionsResponse\"3\x82\xb5\x18\a\x12\x05admin\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/ledger/transactions/query\x12x\n" +
	"\fListPostings\x12\x17.v1.ListPostingsRequest\x1a\x18.v1.ListPostingsResponse\"5\x82\xb5\x18\r\x12\x05admin\x12\x04user\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/ledger/postings/queryB6Z4github.com/squall-chua/go-ledger-microservice/api/v1b\x06proto3"

var (
	file_api_proto_v1_ledger_proto_rawDescOnce sync.Once
	file_api_proto_v1_ledger_proto_rawDescData []byte
)

func file_api_proto_v1_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)))
	})
	return file_api_proto_v1_ledger_proto_rawDescData
}

var file_api_proto_v1_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_v1_ledger_proto_goTypes = []any{
	(AccountType)(0),                              // 0: v1.AccountType
	(MetadataFilter_Operator)(0),                  // 1: v1.MetadataFilter.Operator
	(*AccountName)(nil),                           // 2: v1.AccountName
	(*Posting)(nil),                               // 3: v1.Posting
	(*Transaction)(nil),                           // 4: v1.Transaction
	(*RecordTransactionRequest)(nil),              // 5: v1.RecordTransactionRequest
	(*RecordTransactionResponse)(nil),             // 6: v1.RecordTransactionResponse
	(*GetAccountBalanceRequest)(nil),              // 7: v1.GetAccountBalanceRequest
	(*GetAccountBalanceResponse)(nil),             // 8: v1.GetAccountBalanceResponse
	(*AccountBalance)(nil),                        // 9: v1.AccountBalance
	(*MetadataFilter)(nil),                        // 10: v1.MetadataFilter
	(*TransactionFilter)(nil),                     // 11: v1.TransactionFilter
	(*ListTransactionsRequest)(nil),               // 12: v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),              // 13: v1.ListTransactionsResponse
	(*PostingFilter)(nil),                         // 14: v1.PostingFilter
	(*ListPostingsRequest)(nil),                   // 15: v1.ListPostingsRequest
	(*ListPostingsResponse)(nil),                  // 16: v1.ListPostingsResponse
	nil,                                           // 17: v1.Transaction.MetadataEntry
	nil,                                           // 18: v1.RecordTransactionRequest.MetadataEntry
	(*RecordTransactionRequest_PostingInput)(nil), // 19: v1.RecordTransactionRequest.PostingInput
	(*money.Money)(nil),                           // 20: google.type.Money
	(*timestamppb.Timestamp)(nil),                 // 21: google.protobuf.Timestamp
	(*anypb.Any)(nil),                             // 22: google.protobuf.Any
}
var file_api_proto_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: v1.AccountName.type:type_name -> v1.AccountType
	2,  // 1: v1.Posting.account:type_name -> v1.AccountName
	20, // 2: v1.Posting.amount:type_name -> google.type.Money
	20, // 3: v1.Posting.balance:type_name -> google.type.Money
	21, // 4: v1.Posting.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: v1.Transaction.date:type_name -> google.protobuf.Timestamp
	17, // 6: v1.Transaction.metadata:type_name -> v1.Transaction.MetadataEntry
	3,  // 7: v1.Transaction.postings:type_name -> v1.Posting
	21, // 8: v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	21, // 9: v1.RecordTransactionRequest.date:type_name -> google.protobuf.Timestamp
	18, // 10: v1.RecordTransactionRequest.metadata:type_name -> v1.RecordTransactionRequest.MetadataEntry
	19, // 11: v1.RecordTransactionRequest.postings:type_name -> v1.RecordTransactionRequest.PostingInput
	2,  // 12: v1.RecordTransactionRequest.verify_non_negative_balances:type_name -> v1.AccountName
	4,  // 13: v1.RecordTransactionResponse.transaction:type_name -> v1.Transaction
	2,  // 14: v1.GetAccountBalanceRequest.account:type_name -> v1.AccountName
	9,  // 15: v1.GetAccountBalanceResponse.balances:type_name -> v1.AccountBalance
	2,  // 16: v1.AccountBalance.account:type_name -> v1.AccountName
	20, // 17: v1.AccountBalance.balance:type_name -> google.type.Money
	21, // 18: v1.AccountBalance.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 19: v1.MetadataFilter.operator:type_name -> v1.MetadataFilter.Operator
	22, // 20: v1.MetadataFilter.value:type_name -> google.protobuf.Any
	21, // 21: v1.TransactionFilter.start_date:type_name -> google.protobuf.Timestamp
	21, // 22: v1.TransactionFilter.end_date:type_name -> google.protobuf.Timestamp
	10, // 23: v1.TransactionFilter.metadata_filters:type_name -> v1.MetadataFilter
	11, // 24: v1.ListTransactionsRequest.filter:type_name -> v1.TransactionFilter
	4,  // 25: v1.ListTransactionsResponse.transactions:type_name -> v1.Transaction
	11, // 26: v1.PostingFilter.transaction_filter:type_name -> v1.TransactionFilter
	2,  // 27: v1.PostingFilter.account:type_name -> v1.AccountName
	14, // 28: v1.ListPostingsRequest.filter:type_name -> v1.PostingFilter
	3,  // 29: v1.ListPostingsResponse.postings:type_name -> v1.Posting
	22, // 30: v1.Transaction.MetadataEntry.value:type_name -> google.protobuf.Any
	22, // 31: v1.RecordTransactionRequest.MetadataEntry.value:type_name -> google.protobuf.Any
	2,  // 32: v1.RecordTransactionRequest.PostingInput.account:type_name -> v1.AccountName
	20, // 33: v1.RecordTransactionRequest.PostingInput.amount:type_name -> google.type.Money
	5,  // 34: v1.LedgerService.RecordTransaction:input_type -> v1.RecordTransactionRequest
	7,  // 35: v1.LedgerService.GetAccountBalance:input_type -> v1.GetAccountBalanceRequest
	12, // 36: v1.LedgerService.ListTransactions:input_type -> v1.ListTransactionsRequest
	15, // 37: v1.LedgerService.ListPostings:input_type -> v1.ListPostingsRequest
	6,  // 38: v1.LedgerService.RecordTransaction:output_type -> v1.RecordTransactionResponse
	8,  // 39: v1.LedgerService.GetAccountBalance:output_type -> v1.GetAccountBalanceResponse
	13, // 40: v1.LedgerService.ListTransactions:output_type -> v1.ListTransactionsResponse
	16, // 41: v1.LedgerService.ListPostings:output_type -> v1.ListPostingsResponse
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ledger_proto_init() }
func file_api_proto_v1_ledger_proto_init() {
	if File_api_proto_v1_ledger_proto != nil {
		return
	}
	file_api_proto_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ledger_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_ledger_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ledger_proto = out.File
	file_api_proto_v1_ledger_proto_goTypes = nil
	file_api_proto_v1_ledger_proto_depIdxs = nil
}
