// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/ledger.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSETS      AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITIES AccountType = 2
	AccountType_ACCOUNT_TYPE_EQUITIES    AccountType = 3
	AccountType_ACCOUNT_TYPE_INCOMES     AccountType = 4
	AccountType_ACCOUNT_TYPE_EXPENSES    AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSETS",
		2: "ACCOUNT_TYPE_LIABILITIES",
		3: "ACCOUNT_TYPE_EQUITIES",
		4: "ACCOUNT_TYPE_INCOMES",
		5: "ACCOUNT_TYPE_EXPENSES",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSETS":      1,
		"ACCOUNT_TYPE_LIABILITIES": 2,
		"ACCOUNT_TYPE_EQUITIES":    3,
		"ACCOUNT_TYPE_INCOMES":     4,
		"ACCOUNT_TYPE_EXPENSES":    5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_ledger_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_ledger_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

// An Account is identified by the exact composite (type, user, name). There is
// no hierarchy, no wildcard and no roll-up: `name` is opaque and every field is
// matched exactly. See docs/adr/0002-flat-account-names.md.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=v1.AccountType" json:"type,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // Free-form owner label. Never an authenticated identity.
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // Opaque label, e.g. "Checking". Never split, never rolled up.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Account       *Account               `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Amount        *money.Money           `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance       *money.Money           `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"` // Running balance of the Account after this leg.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"` // Transaction date: supplied by the caller or stamped by the ledger.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Posting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Posting) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Posting) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Posting) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Posting) GetBalance() *money.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Posting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Posting) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Note           string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postings       []*Posting             `protobuf:"bytes,6,rep,name=postings,proto3" json:"postings,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transaction) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RecordTransactionRequest struct {
	state                     protoimpl.MessageState                   `protogen:"open.v1"`
	IdempotencyKey            string                                   `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Date                      *timestamppb.Timestamp                   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Note                      string                                   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Metadata                  map[string]string                        `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Postings                  []*RecordTransactionRequest_PostingInput `protobuf:"bytes,5,rep,name=postings,proto3" json:"postings,omitempty"`
	VerifyNonNegativeBalances []*Account                               `protobuf:"bytes,6,rep,name=verify_non_negative_balances,json=verifyNonNegativeBalances,proto3" json:"verify_non_negative_balances,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RecordTransactionRequest) Reset() {
	*x = RecordTransactionRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionRequest) ProtoMessage() {}

func (x *RecordTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionRequest.ProtoReflect.Descriptor instead.
func (*RecordTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *RecordTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RecordTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RecordTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RecordTransactionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecordTransactionRequest) GetPostings() []*RecordTransactionRequest_PostingInput {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *RecordTransactionRequest) GetVerifyNonNegativeBalances() []*Account {
	if x != nil {
		return x.VerifyNonNegativeBalances
	}
	return nil
}

type RecordTransactionResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// True when this was an Idempotency replay: the key had already recorded
	// this exact content, so the original Transaction is returned and nothing
	// new was written.
	Replayed      bool `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionResponse) Reset() {
	*x = RecordTransactionResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionResponse) ProtoMessage() {}

func (x *RecordTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionResponse.ProtoReflect.Descriptor instead.
func (*RecordTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *RecordTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RecordTransactionResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

// An AccountFilter narrows a read to the Accounts whose fields match it
// exactly. A field it leaves unset is not filtered on at all; a field it sets
// to the empty string matches only the empty string, so an Account with no
// user can be asked for on its own. Nothing here is ever a wildcard.
type AccountFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=v1.AccountType" json:"type,omitempty"` // Unspecified means "not filtered": no Account carries it.
	User          *string                `protobuf:"bytes,2,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountFilter) Reset() {
	*x = AccountFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFilter) ProtoMessage() {}

func (x *AccountFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFilter.ProtoReflect.Descriptor instead.
func (*AccountFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *AccountFilter) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AccountFilter) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *AccountFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Every filter is optional; supplying none returns the Trial balance.
type ListAccountBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountFilter         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountBalancesRequest) Reset() {
	*x = ListAccountBalancesRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountBalancesRequest) ProtoMessage() {}

func (x *ListAccountBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountBalancesRequest.ProtoReflect.Descriptor instead.
func (*ListAccountBalancesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccountBalancesRequest) GetAccount() *AccountFilter {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ListAccountBalancesRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type ListAccountBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*AccountBalance      `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountBalancesResponse) Reset() {
	*x = ListAccountBalancesResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountBalancesResponse) ProtoMessage() {}

func (x *ListAccountBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountBalancesResponse.ProtoReflect.Descriptor instead.
func (*ListAccountBalancesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountBalancesResponse) GetBalances() []*AccountBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type AccountBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Balance       *money.Money           `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *AccountBalance) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountBalance) GetBalance() *money.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AccountBalance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Every filter is optional. The date range is half-open: start_date is
// included and end_date is excluded, so adjacent periods never double-count.
type TransactionFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Exact; matches at most one Transaction.
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                // Transaction date, inclusive.
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                      // Transaction date, exclusive.
	// Exact metadata pairs the Transaction has to carry. Every pair given has
	// to match, key and value; a Transaction carrying more is still a match. An
	// empty key is refused.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionFilter) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactionFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TransactionFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *TransactionFilter) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListTransactionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Filter           *TransactionFilter     `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                           // Defaults to 10, clamped to at most 100.
	PageNumber       int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`                     // One-based; below one is the first page.
	OrderByAscending bool                   `protobuf:"varint,4,opt,name=order_by_ascending,json=orderByAscending,proto3" json:"order_by_ascending,omitempty"` // Oldest Transaction date first. Default is newest first.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListTransactionsRequest) GetOrderByAscending() bool {
	if x != nil {
		return x.OrderByAscending
	}
	return false
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// A Register read: one Account's Postings over time. Every filter is optional
// and the date range is half-open, as on the Transaction listing.
type PostingFilter struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Account      *AccountFilter         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CurrencyCode string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	StartDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Transaction date, inclusive.
	EndDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Transaction date, exclusive.
	// Matched against the parent Transaction's metadata — a Posting has none of
	// its own. Same exact-pair rule as on the Transaction listing.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostingFilter) Reset() {
	*x = PostingFilter{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingFilter) ProtoMessage() {}

func (x *PostingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingFilter.ProtoReflect.Descriptor instead.
func (*PostingFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *PostingFilter) GetAccount() *AccountFilter {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *PostingFilter) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *PostingFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *PostingFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *PostingFilter) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListPostingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Filter           *PostingFilter         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                           // Defaults to 10, clamped to at most 100.
	PageNumber       int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`                     // One-based; below one is the first page.
	OrderByAscending bool                   `protobuf:"varint,4,opt,name=order_by_ascending,json=orderByAscending,proto3" json:"order_by_ascending,omitempty"` // Oldest Transaction date first. Default is newest first.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPostingsRequest) Reset() {
	*x = ListPostingsRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostingsRequest) ProtoMessage() {}

func (x *ListPostingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostingsRequest.ProtoReflect.Descriptor instead.
func (*ListPostingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostingsRequest) GetFilter() *PostingFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListPostingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPostingsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListPostingsRequest) GetOrderByAscending() bool {
	if x != nil {
		return x.OrderByAscending
	}
	return false
}

type ListPostingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostingsResponse) Reset() {
	*x = ListPostingsResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostingsResponse) ProtoMessage() {}

func (x *ListPostingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostingsResponse.ProtoReflect.Descriptor instead.
func (*ListPostingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *ListPostingsResponse) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *ListPostingsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RecordTransactionRequest_PostingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount        *money.Money           `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionRequest_PostingInput) Reset() {
	*x = RecordTransactionRequest_PostingInput{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionRequest_PostingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionRequest_PostingInput) ProtoMessage() {}

func (x *RecordTransactionRequest_PostingInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionRequest_PostingInput.ProtoReflect.Descriptor instead.
func (*RecordTransactionRequest_PostingInput) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RecordTransactionRequest_PostingInput) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RecordTransactionRequest_PostingInput) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_api_proto_v1_ledger_proto protoreflect.FileDescriptor

const file_api_proto_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/ledger.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/type/money.proto\x1a\x1aapi/proto/v1/options.proto\"V\n" +
	"\aAccount\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.v1.AccountTypeR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xac\x02\n" +
	"\aPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12%\n" +
	"\aaccount\x18\x03 \x01(\v2\v.v1.AccountR\aaccount\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.google.type.MoneyR\x06amount\x12,\n" +
	"\abalance\x18\x05 \x01(\v2\x12.google.type.MoneyR\abalance\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xe6\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x129\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1d.v1.Transaction.MetadataEntryR\bmetadata\x12'\n" +
	"\bpostings\x18\x06 \x03(\v2\v.v1.PostingR\bpostings\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x04\n" +
	"\x18RecordTransactionRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.v1.RecordTransactionRequest.MetadataEntryR\bmetadata\x12E\n" +
	"\bpostings\x18\x05 \x03(\v2).v1.RecordTransactionRequest.PostingInputR\bpostings\x12L\n" +
	"\x1cverify_non_negative_balances\x18\x06 \x03(\v2\v.v1.AccountR\x19verifyNonNegativeBalances\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\fPostingInput\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.v1.AccountR\aaccount\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.google.type.MoneyR\x06amount\"j\n" +
	"\x19RecordTransactionResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.v1.TransactionR\vtransaction\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\"x\n" +
	"\rAccountFilter\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.v1.AccountTypeR\x04type\x12\x17\n" +
	"\x04user\x18\x02 \x01(\tH\x00R\x04user\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01B\a\n" +
	"\x05_userB\a\n" +
	"\x05_name\"n\n" +
	"\x1aListAccountBalancesRequest\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.v1.AccountFilterR\aaccount\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\"M\n" +
	"\x1bListAccountBalancesResponse\x12.\n" +
	"\bbalances\x18\x01 \x03(\v2\x12.v1.AccountBalanceR\bbalances\"\xa0\x01\n" +
	"\x0eAccountBalance\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.v1.AccountR\aaccount\x12,\n" +
	"\abalance\x18\x02 \x01(\v2\x12.google.type.MoneyR\abalance\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\x11TransactionFilter\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.v1.TransactionFilter.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x17ListTransactionsRequest\x12-\n" +
	"\x06filter\x18\x01 \x01(\v2\x15.v1.TransactionFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12,\n" +
	"\x12order_by_ascending\x18\x04 \x01(\bR\x10orderByAscending\"p\n" +
	"\x18ListTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xcd\x02\n" +
	"\rPostingFilter\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.v1.AccountFilterR\aaccount\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.v1.PostingFilter.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x13ListPostingsRequest\x12)\n" +
	"\x06filter\x18\x01 \x01(\v2\x11.v1.PostingFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12,\n" +
	"\x12order_by_ascending\x18\x04 \x01(\bR\x10orderByAscending\"`\n" +
	"\x14ListPostingsResponse\x12'\n" +
	"\bpostings\x18\x01 \x03(\v2\v.v1.PostingR\bpostings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount*\xb2\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACCOUNT_TYPE_ASSETS\x10\x01\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_LIABILITIES\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_TYPE_EQUITIES\x10\x03\x12\x18\n" +
	"\x14ACCOUNT_TYPE_INCOMES\x10\x04\x12\x19\n" +
	"\x15ACCOUNT_TYPE_EXPENSES\x10\x052\xaf\x04\n" +
	"\rLedgerService\x12\x86\x01\n" +
	"\x11RecordTransaction\x12\x1c.v1.RecordTransactionRequest\x1a\x1d.v1.RecordTransactionResponse\"4\x82\xb5\x18\x0e\n" +
	"\fledger:write\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/ledger/transactions\x12\x8f\x01\n" +
	"\x13ListAccountBalances\x12\x1e.v1.ListAccountBalancesRequest\x1a\x1f.v1.ListAccountBalancesResponse\"7\x82\xb5\x18\r\n" +
	"\vledger:read\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/ledger/accounts/balance\x12\x88\x01\n" +
	"\x10ListTransactions\x12\x1b.v1.ListTransactionsRequest\x1a\x1c.v1.ListTransactionsResponse\"9\x82\xb5\x18\r\n" +
	"\vledger:read\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/ledger/transactions/query\x12x\n" +
	"\fListPostings\x12\x17.v1.ListPostingsRequest\x1a\x18.v1.ListPostingsResponse\"5\x82\xb5\x18\r\n" +
	"\vledger:read\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/ledger/postings/queryB6Z4github.com/squall-chua/go-ledger-microservice/api/v1b\x06proto3"

var (
	file_api_proto_v1_ledger_proto_rawDescOnce sync.Once
	file_api_proto_v1_ledger_proto_rawDescData []byte
)

func file_api_proto_v1_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)))
	})
	return file_api_proto_v1_ledger_proto_rawDescData
}

var file_api_proto_v1_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_v1_ledger_proto_goTypes = []any{
	(AccountType)(0),                              // 0: v1.AccountType
	(*Account)(nil),                               // 1: v1.Account
	(*Posting)(nil),                               // 2: v1.Posting
	(*Transaction)(nil),                           // 3: v1.Transaction
	(*RecordTransactionRequest)(nil),              // 4: v1.RecordTransactionRequest
	(*RecordTransactionResponse)(nil),             // 5: v1.RecordTransactionResponse
	(*AccountFilter)(nil),                         // 6: v1.AccountFilter
	(*ListAccountBalancesRequest)(nil),            // 7: v1.ListAccountBalancesRequest
	(*ListAccountBalancesResponse)(nil),           // 8: v1.ListAccountBalancesResponse
	(*AccountBalance)(nil),                        // 9: v1.AccountBalance
	(*TransactionFilter)(nil),                     // 10: v1.TransactionFilter
	(*ListTransactionsRequest)(nil),               // 11: v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),              // 12: v1.ListTransactionsResponse
	(*PostingFilter)(nil),                         // 13: v1.PostingFilter
	(*ListPostingsRequest)(nil),                   // 14: v1.ListPostingsRequest
	(*ListPostingsResponse)(nil),                  // 15: v1.ListPostingsResponse
	nil,                                           // 16: v1.Transaction.MetadataEntry
	nil,                                           // 17: v1.RecordTransactionRequest.MetadataEntry
	(*RecordTransactionRequest_PostingInput)(nil), // 18: v1.RecordTransactionRequest.PostingInput
	nil,                           // 19: v1.TransactionFilter.MetadataEntry
	nil,                           // 20: v1.PostingFilter.MetadataEntry
	(*money.Money)(nil),           // 21: google.type.Money
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_api_proto_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: v1.Account.type:type_name -> v1.AccountType
	1,  // 1: v1.Posting.account:type_name -> v1.Account
	21, // 2: v1.Posting.amount:type_name -> google.type.Money
	21, // 3: v1.Posting.balance:type_name -> google.type.Money
	22, // 4: v1.Posting.created_at:type_name -> google.protobuf.Timestamp
	22, // 5: v1.Posting.date:type_name -> google.protobuf.Timestamp
	22, // 6: v1.Transaction.date:type_name -> google.protobuf.Timestamp
	16, // 7: v1.Transaction.metadata:type_name -> v1.Transaction.MetadataEntry
	2,  // 8: v1.Transaction.postings:type_name -> v1.Posting
	22, // 9: v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	22, // 10: v1.RecordTransactionRequest.date:type_name -> google.protobuf.Timestamp
	17, // 11: v1.RecordTransactionRequest.metadata:type_name -> v1.RecordTransactionRequest.MetadataEntry
	18, // 12: v1.RecordTransactionRequest.postings:type_name -> v1.RecordTransactionRequest.PostingInput
	1,  // 13: v1.RecordTransactionRequest.verify_non_negative_balances:type_name -> v1.Account
	3,  // 14: v1.RecordTransactionResponse.transaction:type_name -> v1.Transaction
	0,  // 15: v1.AccountFilter.type:type_name -> v1.AccountType
	6,  // 16: v1.ListAccountBalancesRequest.account:type_name -> v1.AccountFilter
	9,  // 17: v1.ListAccountBalancesResponse.balances:type_name -> v1.AccountBalance
	1,  // 18: v1.AccountBalance.account:type_name -> v1.Account
	21, // 19: v1.AccountBalance.balance:type_name -> google.type.Money
	22, // 20: v1.AccountBalance.updated_at:type_name -> google.protobuf.Timestamp
	22, // 21: v1.TransactionFilter.start_date:type_name -> google.protobuf.Timestamp
	22, // 22: v1.TransactionFilter.end_date:type_name -> google.protobuf.Timestamp
	19, // 23: v1.TransactionFilter.metadata:type_name -> v1.TransactionFilter.MetadataEntry
	10, // 24: v1.ListTransactionsRequest.filter:type_name -> v1.TransactionFilter
	3,  // 25: v1.ListTransactionsResponse.transactions:type_name -> v1.Transaction
	6,  // 26: v1.PostingFilter.account:type_name -> v1.AccountFilter
	22, // 27: v1.PostingFilter.start_date:type_name -> google.protobuf.Timestamp
	22, // 28: v1.PostingFilter.end_date:type_name -> google.protobuf.Timestamp
	20, // 29: v1.PostingFilter.metadata:type_name -> v1.PostingFilter.MetadataEntry
	13, // 30: v1.ListPostingsRequest.filter:type_name -> v1.PostingFilter
	2,  // 31: v1.ListPostingsResponse.postings:type_name -> v1.Posting
	1,  // 32: v1.RecordTransactionRequest.PostingInput.account:type_name -> v1.Account
	21, // 33: v1.RecordTransactionRequest.PostingInput.amount:type_name -> google.type.Money
	4,  // 34: v1.LedgerService.RecordTransaction:input_type -> v1.RecordTransactionRequest
	7,  // 35: v1.LedgerService.ListAccountBalances:input_type -> v1.ListAccountBalancesRequest
	11, // 36: v1.LedgerService.ListTransactions:input_type -> v1.ListTransactionsRequest
	14, // 37: v1.LedgerService.ListPostings:input_type -> v1.ListPostingsRequest
	5,  // 38: v1.LedgerService.RecordTransaction:output_type -> v1.RecordTransactionResponse
	8,  // 39: v1.LedgerService.ListAccountBalances:output_type -> v1.ListAccountBalancesResponse
	12, // 40: v1.LedgerService.ListTransactions:output_type -> v1.ListTransactionsResponse
	15, // 41: v1.LedgerService.ListPostings:output_type -> v1.ListPostingsResponse
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ledger_proto_init() }
func file_api_proto_v1_ledger_proto_init() {
	if File_api_proto_v1_ledger_proto != nil {
		return
	}
	file_api_proto_v1_options_proto_init()
	file_api_proto_v1_ledger_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ledger_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_ledger_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ledger_proto = out.File
	file_api_proto_v1_ledger_proto_goTypes = nil
	file_api_proto_v1_ledger_proto_depIdxs = nil
}
